{% set name = "dwave-samplers" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dwavesystems/dwave-samplers/archive/refs/tags/{{ version }}.tar.gz
  sha256: 86e125c4084ba70cd6a3404299c8c15001c6c3128959b31adc0bb3684c3dbc63

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0,<4.0                      # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - dimod >=0.12.17,<0.13.0                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - numpy
    - cython >=3.0,<4.0
    - dimod >=0.12.0,<0.13.0
    - pip
    - setuptools >=46.4.0
    - wheel >=0.30.0
  run:
    - python
    - dimod >=0.12.17,<0.13.0
    - networkx >=3.0

test:
  imports:
    - dwave
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-samplers
  summary: Ocean-compatible collection of solvers/samplers
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
