{% set name = "dwave-samplers" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dwavesystems/dwave-samplers/archive/refs/tags/{{ version }}.tar.gz
  sha256: ed4b3a4e3da76c35dfb3d70e4bb45fe3c0b5eb277115d41894381cf8c9cd5999

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0,<4.0                      # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - dimod >=0.12.0,<0.13.0                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - numpy
    - cython >=3.0,<4.0
    - dimod >=0.12.0,<0.13.0
    - pip
    - setuptools >=46.4.0
    - wheel >=0.30.0
  run:
    - python
    - dimod >=0.12.13,<0.13.0
    - networkx >=3.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - dwave
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-samplers
  summary: Ocean-compatible collection of solvers/samplers
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
