{% set name = "dwave-samplers" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dwavesystems/dwave-samplers/archive/refs/tags/{{ version }}.tar.gz
  sha256: d28df71dd653a825ac7edccaccd6b625bffab1169aca7f09b37418187c40ea71

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - dimod >=0.12.0,<0.13.0                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - cython >=0.29.24,<3.0
    - dimod >=0.12.0,<0.13.0
    - pip
    - setuptools >=46.4.0
    - wheel >=0.30.0
  run:
    - python
    - dimod >=0.12.0,<0.13.0
    - networkx >=2.4.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - dwave
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-samplers
  summary: Ocean-compatible collection of solvers/samplers
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
